name: MobChunk
version: '1.1.0'
main: net.fameless.mobchunk.MobChunkPlugin
api-version: '1.20'
author: Fameless9

commands:
  timer:
    permission: mobchunk.timer
  skip:
    permission: mobchunk.skip
  language:
    permission: mobchunk.language